server:
  port: ${SERVER_PORT}

spring:
  application:
    name: socket-jam-socket
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jwt:
    public-key-file: keys/public.pem
  cloud:
    stream:
      bindings:
        socketConnectedEvent-out-0:
          destination: socket-jam.socket.connected
        socketDisconnectedEvent-out-0:
          destination: socket-jam.socket.disconnected
      kafka:
        binder:
          brokers: ${KAFKA_HOST}:${KAFKA_PORT}

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: "http://${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka"
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5