server:
  port: 8082

spring:
  application:
    name: socket-jam-socket
  data:
    redis:
      password: ${REDIS_PASSWORD}
  jwt:
    public-key-file: keys/public.pem

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5